-- =====================================================================
-- STEP 1: INITIALIZE SCHEMAS & INFRASTRUCTURE
-- =====================================================================
CREATE DATABASE IF NOT EXISTS HACKATHON_COMPLIANCE_DB;
USE DATABASE HACKATHON_COMPLIANCE_DB;
CREATE SCHEMA IF NOT EXISTS RISK_INTELLIGENCE_SCHEMA;
USE SCHEMA RISK_INTELLIGENCE_SCHEMA;

-- =====================================================================
-- STEP 2: TABLE DOMAINS
-- =====================================================================

-- Account Master with Lifecycle Fields
CREATE OR REPLACE TABLE ACCOUNT_MASTER (
    ACCOUNT_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    KYC_STATUS VARCHAR(20),                -- 'VERIFIED', 'UNVERIFIED', 'EXPIRED'
    RISK_SCORE INT,                       -- Range: 0 to 100
    ACCOUNT_TYPE VARCHAR(30),             -- 'RETAIL', 'CORPORATE', 'HNI'
    KYC_VERIFICATION_DATE DATE,           
    KYC_EXPIRY_DATE DATE,                 
    RECOMMENDED_REVERIFICATION_DATE DATE,  
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Transaction Ledger tracking Merchant Fields & Velocity Spikes
CREATE OR REPLACE TABLE TRANSACTION_LEDGER (
    TRANSACTION_ID VARCHAR(64) PRIMARY KEY, 
    ACCOUNT_ID VARCHAR(50) FOREIGN KEY REFERENCES ACCOUNT_MASTER(ACCOUNT_ID),
    AMOUNT NUMBER(18, 2),
    CURRENCY VARCHAR(3) DEFAULT 'INR',
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    MERCHANT_CATEGORY VARCHAR(50),        
    RISK_INTENSITY VARCHAR(20)            -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
);

-- Complete Audit Submission repository
CREATE OR REPLACE TABLE SUSPICIOUS_TRANSACTION_REPORTS (
    STR_REPORT_ID VARCHAR(50) PRIMARY KEY,
    SIGNAL_HASH VARCHAR(64),              
    ACCOUNT_ID VARCHAR(50),               
    EVIDENCE_CHUNK_ID VARCHAR(50),        
    REGULATORY_CLAUSE_MAPPING TEXT,       
    GENERATED_REPORT_MD TEXT,             
    IS_FLAGGED_FOR_AUDIT BOOLEAN DEFAULT TRUE,
    GENERATED_BY_USER VARCHAR(100),       
    GENERATION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================================================
-- STEP 3: ANALYTICS VIEWS & PROCEDURES (Direct UI Hooks)
-- =====================================================================

-- Secure View capturing 48-Hour High Exposure Spikes
CREATE OR REPLACE SECURE VIEW V_FLAGGED_ACCOUNTS_48HR_VELOCITY AS
SELECT 
    TRANSACTION_ID,
    ACCOUNT_ID,
    AMOUNT,
    MERCHANT_CATEGORY,
    TRANSACTION_TIMESTAMP
FROM TRANSACTION_LEDGER
WHERE TRANSACTION_TIMESTAMP >= DATEADD('hour', -48, CURRENT_TIMESTAMP())
ORDER BY TRANSACTION_TIMESTAMP DESC;

-- Pre-Compiled Audit View mapping regulatory clauses
CREATE OR REPLACE VIEW V_AUDIT_SUBMISSION_EXPORT AS 
SELECT 
    STR_REPORT_ID, 
    ACCOUNT_ID, 
    SIGNAL_HASH AS TRANSACTION_HASH, 
    REGULATORY_CLAUSE_MAPPING, 
    GENERATED_REPORT_MD 
FROM SUSPICIOUS_TRANSACTION_REPORTS
WHERE IS_FLAGGED_FOR_AUDIT = TRUE
LIMIT 5;

-- Stored Procedure calculating 30-Day Mandatory KYC Remediation Windows
CREATE OR REPLACE PROCEDURE AUDIT_KYC_STATUS_LIFECYCLE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE ACCOUNT_MASTER
    SET RECOMMENDED_REVERIFICATION_DATE = DATEADD('day', 30, CURRENT_DATE())
    WHERE KYC_STATUS = 'EXPIRED' OR KYC_EXPIRY_DATE <= CURRENT_DATE();
    
    RETURN 'KYC Lifecycle audited and re-verification recommendations successfully updated.';
END;
$$;
