USE DATABASE HACKATHON_COMPLIANCE_DB;
USE SCHEMA RISK_INTELLIGENCE_SCHEMA;

-- 1. CLEAN CONTEXT FOR FRESH REPLICA
DELETE FROM TRANSACTION_LEDGER;
DELETE FROM ACCOUNT_MASTER;
DELETE FROM SUSPICIOUS_TRANSACTION_REPORTS;

-- 2. PLANT DISCOVERY ACCOUNTS
INSERT INTO ACCOUNT_MASTER (ACCOUNT_ID, CUSTOMER_NAME, KYC_STATUS, RISK_SCORE, ACCOUNT_TYPE, KYC_VERIFICATION_DATE, KYC_EXPIRY_DATE)
VALUES 
('ACC-101', 'Acme FinTech Corp', 'EXPIRED', 89, 'CORPORATE', '2024-01-15', '2026-01-15'),
('ACC-102', 'Rajesh Kumar HNI', 'EXPIRED', 94, 'HNI', '2023-06-20', '2025-06-20'),
('ACC-103', 'Alpha Trading LLC', 'EXPIRED', 82, 'CORPORATE', '2024-03-10', '2026-03-10'),
('ACC-104', 'Vikas Sharma Retail', 'VERIFIED', 45, 'RETAIL', '2025-01-01', '2027-01-01'),
('ACC-105', 'Zeta Global Assets', 'UNVERIFIED', 91, 'CORPORATE', '2025-05-12', '2026-05-12');

-- 3. PLANT ANCHOR ANOMALIES
INSERT INTO TRANSACTION_LEDGER (TRANSACTION_ID, ACCOUNT_ID, AMOUNT, TRANSACTION_TIMESTAMP, MERCHANT_CATEGORY, RISK_INTENSITY)
VALUES 
('TX-ALRT-001', 'ACC-101', 750000.00, DATEADD('hour', -4, CURRENT_TIMESTAMP()), 'CRYPTO_EXCHANGE', 'CRITICAL'),
('TX-ALRT-002', 'ACC-102', 980000.00, DATEADD('hour', -12, CURRENT_TIMESTAMP()), 'OFFSHORE_GAMING', 'CRITICAL'),
('TX-ALRT-003', 'ACC-105', 1250000.00, DATEADD('hour', -18, CURRENT_TIMESTAMP()), 'FOREIGN_SHELL', 'CRITICAL');

-- 4. BULK ENGINE SEED (100+ Transaction Data Flow Generator)
INSERT INTO TRANSACTION_LEDGER (TRANSACTION_ID, ACCOUNT_ID, AMOUNT, TRANSACTION_TIMESTAMP, MERCHANT_CATEGORY, RISK_INTENSITY)
SELECT 
    'TX-GEN-' || SEQ4() AS TRANSACTION_ID,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'ACC-101'
        WHEN 1 THEN 'ACC-102'
        WHEN 2 THEN 'ACC-103'
        WHEN 3 THEN 'ACC-104'
        ELSE 'ACC-105'
    END AS ACCOUNT_ID,
    UNIFORM(5000.00, 680000.00, RANDOM()) AS AMOUNT,
    DATEADD('minute', -UNIFORM(10, 2800, RANDOM()), CURRENT_TIMESTAMP()) AS TRANSACTION_TIMESTAMP,
    CASE MOD(SEQ4(), 6)
        WHEN 0 THEN 'CRYPTO_EXCHANGE'
        WHEN 1 THEN 'OFFSHORE_GAMING'
        WHEN 2 THEN 'FOREIGN_SHELL'
        WHEN 3 THEN 'LUXURY_ASSETS'
        WHEN 4 THEN 'TECH_SUPPLY'
        ELSE 'RETAIL_ECOM'
    END AS MERCHANT_CATEGORY,
    CASE 
        WHEN UNIFORM(5000.00, 680000.00, RANDOM()) > 500000 THEN 'CRITICAL'
        WHEN UNIFORM(5000.00, 680000.00, RANDOM()) > 250000 THEN 'HIGH'
        ELSE 'LOW'
    END AS RISK_INTENSITY
FROM TABLE(GENERATOR(ROWCOUNT => 100));

-- 5. SEED WORKFLOW ARCHIVE SUBMISSIONS
INSERT INTO SUSPICIOUS_TRANSACTION_REPORTS (STR_REPORT_ID, SIGNAL_HASH, ACCOUNT_ID, EVIDENCE_CHUNK_ID, REGULATORY_CLAUSE_MAPPING, GENERATED_REPORT_MD, GENERATED_BY_USER)
VALUES 
('STR-001', 'TX-ALRT-001', 'ACC-101', 'RBI-AML-SEC38', 'RBI Directions Sec 38(b): High-Velocity Crypto Spikes', 
 '### STR AUDIT FILE\n* Account `ACC-101` executed a spike of **₹7,50,000** under an expired KYC state.\n* **Regulatory Citation:** RBI AML Master Circular Clause 38.', 'azure-admin-copilot@enterprise.com'),
('STR-002', 'TX-ALRT-002', 'ACC-102', 'RBI-AML-SEC12', 'RBI Directions Sec 12(a): High-Risk Gaming Outflows', 
 '### STR AUDIT FILE\n* Account `ACC-102` routed **₹9,80,000** into an offshore gaming domain.\n* **Regulatory Citation:** RBI Velocity Safeguard Framework.', 'azure-admin-copilot@enterprise.com');
